### ISSUE TITLE
Include sample sounding data file.

### ISSUE THREAD

**Issue by wxguy** [cwebster2/pyMeteo#10]
I have mentioned in one of my earlier issue. I think you must include a sample sounding data file explicitly. So that user does not end up with error log. I have tested your package with freely available actual upper air data from http://weather.uwyo.edu/upperair/sounding.html. Sample data for `72318 RNK Blacksburg` is attached below (changed the extension as github did not allow the '.dat' file extension):-
[sounding.txt](https://github.com/cwebster2/pyMeteo/files/75895/sounding.txt)

Then I applied your sample command listed in Readme file and I received an error message. Log is here:-

```
$ skewt -f docs/data/sounding.dat -o skewt.pdf
Traceback (most recent call last):
  File "/usr/bin/skewt", line 35, in <module>
    skewt.plot_sounding_data(options.fname, out)
  File "/usr/lib/python2.7/site-packages/pymeteo/skewt.py", line 418, in plot_sounding_data
    p0, th0, qv0 = surface.split()
ValueError: need more than 1 value to unpack
```

**Comment by cwebster2** [comment]
Thanks for the reminder.  I've added a data file of the format that function knows how to interpret (WRF / CM1 initial sounding) in `testdata/`.  I'm going to leave this issue open as a feature request for that data and to track progress to implementing it (so I don't forget about it)
- [X] include sample data
- [x] write function to parse uwyo data
- [x] write cli script to ingest this data from a file and plot
- [x] add capability to script to directly fetch data from the uwyo website over http

**Comment by cwebster2** [comment]
Commit 6bcd1bc (latest master commit) has preliminary uwyo plotting capabilities. You can copy/paste from the website into files formatted like the ones in `testdata/` (title on line 1, line 2 blank, lines 3,4,5,6 headers and data starting on line 7).  I'll add ability to pull data from the website directly in a future commit.  Real data is messy, so if you find any soundings that break the plotting, send them my way, or add them in the `testdata/` directory and send me a pull request.

**Comment by cwebster2** [comment]
Latest commit now has support to plot the current sounding from uwyo for a given station id.

```
$ skewt uwyoweb skewt.pdf --station 72251
```
