### ISSUE TITLE
Latest commit breaking compatability with python2 (2.7)

### ISSUE THREAD

**Issue by wxguy** [cwebster2/pyMeteo#12]
I have been trying your code for every feature you include. The latest commit (download from net and plot skewt) breaks the comparability with the python version 2. All bugs I have reported are based on the test conducted on python 2 only.  

I have found that it is due to the spiting of `urllib` package in python3. The same package was `urllib2` in python 2. To overcome this issue I included these lines for `import urllib.request as request`:-

```
import urllib2
from urllib2 import Request
```

This time script run scussesfully but again struck at `skewt.py script` . Here is the terminal output for review:-

```
skewt uwyoweb skewt.pdf --station 72251           
Traceback (most recent call last):
  File "/usr/bin/skewt", line 159, in <module>
    main()
  File "/usr/bin/skewt", line 128, in main
    skewt.plot_sounding_data_uwyo(None, args.output, stationID=args.station)
  File "/usr/lib/python2.7/site-packages/pymeteo/skewt.py", line 482, in plot_sounding_data_uwyo
    date = datetime.datetime.now(datetime.timezone.utc)
AttributeError: 'module' object has no attribute 'timezone'
```

I don't know what causes the problem. You may look into this issue as most of the scientific communities are conservative and not likely to use python 3 for everything.

Probably you can use the try statement for those missing/ depreciated modules which are not present in python 2 and print message to use python 3. That way other features are not affected by it.

On a side note, I really appreciate the kind of dedication you show it to this package.

**Comment by cwebster2** [comment]
I anticipated this would be the case. Ill spool up a 2.7 virtualenv and get it working in that environment too. 

I too appreciate your helpfulness in reporting these issues.

**Comment by liamtill** [comment]
I think this may be related but I kept getting an issue with python 2.7 and 3.5. Both were saying no module called request. Which of course there was when I checked. I was implementing your package to plot skew-t in my own wrf plotting script for python 2.x. To fix this I added the lines above to uwyo.py:

`import urllib2`
`from urllib2 import Request`

and replaced `request` with `Request` then re-ran setup. This seemed to fix that and now it works fine. I didn't test for python 3.5 as my script is in 2.7.

Also great work with this package I've found it very useful. Appreciate it and look forward to future updates.

**Comment by wxguy** [comment]
The bug is still not fixed. See the comment on the commit https://github.com/cwebster2/pyMeteo/commit/253e9e914243955a847f7f58f4ff991d0407f3a1

**Comment by cwebster2** [comment]
Yep, I'll get that fixed tonight.  Thanks. (and fix my 2.7 testing....)

**Comment by cwebster2** [comment]
This should be resolved in master now.  Will do some more testing with python 2 and 3 and then bump the version number and update the pypi package.

**Comment by cwebster2** [comment]
Found another 2.7 problem.  update incoming.
