### ISSUE TITLE
Numpy Arrays

### ISSUE THREAD

**Issue by nlenssen2013** [cwebster2/pyMeteo#15]
N/A

**Comment by cwebster2** [comment]
You do not need to import dew point, that is calculated in `plot_sounding()` using the mixing ratio your provide in the `qv` variable.  My initial guess is that you might have some bad values (or units in the inputs are not what the code is expecting) and the call to `math.exp` or that line in general is blowing up toward infinity (line 63 in thermo.pyc). 

If you can provide me with the inputs you are calling `skewt.plot()` with I can take a look and see if data is the issue.  I can probably catch these errors and provide a little better messages, perhaps in a future release.

**Comment by nlenssen2013** [comment]
I got it to work. Some units issues. Thanks.
