### ISSUE TITLE
Replacing quit() with raising an Exception

### ISSUE THREAD

**Issue by lennard28** [cwebster2/pyMeteo#23]
I'm using pymeteo for 5000+ measurements. Unfortunately there are sometimes calculation, where I'm receiving 'Error: lack of convergence, stopping iteration' and because of the 'quit()' in the next line the programm stops running because of one wrong calculation.
I would appreciate a Replacement of quit() with the raising an Exception, which my programm can catch and continue the calculation.

line 401 of thermo.py
``` python
if i > 100:
    print('Error: lack of convergence, stopping iteration')
    quit()
```

**Comment by cwebster2** [comment]
This change (and a few other quit -> exceptions) is now merged into master.
